/**
 * ============================================================
 *  ISSUE TRACKER CONFIG — Reads projects from ../mods.json
 * ============================================================
 *  mods.json is auto-generated by your GitHub Action.
 *  This file only defines: owner, worker URL, and issue fields.
 * ============================================================
 */

const CONFIG = {
  // ── Your GitHub username (fallback if repo_url parsing fails) ──
  defaultOwner: "Chuckleberry-Finn",

  // ── Hub display ───────────────────────────────────────
  hub: {
    title: "Issue Tracker",
    subtitle: "Report bugs or request features for any mod",
  },

  // ── Cloudflare Worker (Steam auth backend) ────────────
  //    Leave empty to disable Steam login.
  worker: {
    url: "https://steam-issue-tracker.chuckleberryfinn.workers.dev",
  },

  // ── Path to mods.json relative to this page ───────────
  modsJsonPath: "../mods.json",

  // ── Issue types & form fields ─────────────────────────
  issueTypes: {
    bug: {
      label: "Bug Report",
      githubLabel: "bug",
      fields: [
        { id: "title",       label: "Summary",                    type: "text",     required: true,  placeholder: "Brief description of the bug" },
        { id: "severity",    label: "Severity",                   type: "select",   required: true,  options: ["Critical — Game crash / data loss", "High — Major feature broken", "Medium — Minor feature broken", "Low — Cosmetic / visual issue"] },
        { id: "repro",       label: "Steps to Reproduce",         type: "textarea", required: true,  placeholder: "1. Go to...\n2. Click on...\n3. Observe..." },
        { id: "expected",    label: "Expected Behavior",          type: "textarea", required: true,  placeholder: "What should have happened?" },
        { id: "actual",      label: "Actual Behavior",            type: "textarea", required: true,  placeholder: "What actually happened?" },
        { id: "platform",    label: "Platform",                   type: "select",   required: true,  options: ["Windows 10", "Windows 11", "Linux", "macOS", "Steam Deck"] },
        { id: "gameversion", label: "Game Version",               type: "text",     required: false, placeholder: "e.g. Build 42.0.5" },
        { id: "modlist",     label: "Other Active Mods",          type: "textarea", required: false, placeholder: "List other mods you're running (if relevant)" },
        { id: "extra",       label: "Additional Context",         type: "textarea", required: false, placeholder: "Screenshots, log files, system specs, etc." },
      ]
    },
    feature: {
      label: "Feature Request",
      githubLabel: "enhancement",
      fields: [
        { id: "title",       label: "Feature Title",              type: "text",     required: true,  placeholder: "Short, descriptive title" },
        { id: "category",    label: "Category",                   type: "select",   required: true,  options: ["Gameplay", "UI / UX", "Performance", "Compatibility", "Accessibility", "Other"] },
        { id: "description", label: "Description",                type: "textarea", required: true,  placeholder: "Describe the feature you'd like to see" },
        { id: "usecase",     label: "Use Case / Motivation",      type: "textarea", required: true,  placeholder: "Why is this feature valuable? What problem does it solve?" },
        { id: "extra",       label: "Additional Context",         type: "textarea", required: false, placeholder: "Mockups, examples, etc." },
      ]
    }
  },
};
