/**
 * ============================================================
 *  ISSUE TRACKER CONFIG — Reads projects from ../mods.json
 * ============================================================
 *  mods.json is auto-generated by your GitHub Action.
 *  This file only defines: owner, worker URL, and issue fields.
 * ============================================================
 */

const CONFIG = {
  // ── Your GitHub username (fallback if repo_url parsing fails) ──
  defaultOwner: "Chuckleberry-Finn",

  // ── Hub display ───────────────────────────────────────
  hub: {
    title: "Issue Tracker",
    subtitle: "Report bugs or request features for any mod",
  },

  // ── Cloudflare Worker (Steam auth backend) ────────────
  //    Leave empty to disable Steam login.
  worker: {
    url: "https://steam-issue-tracker.chuckleberryfinn.workers.dev",
  },

  // ── Path to mods.json relative to this page ───────────
  modsJsonPath: "../mods.json",

  // ── Issue types & form fields ─────────────────────────
  issueTypes: {
    bug: {
      label: "Bug Report",
      githubLabel: "bug",
      fields: [
        { id: "title",       label: "Title",                    type: "text",     required: true,  placeholder: "Brief descriptive title for the issue",                                    weight: 15, detailBonus: { min: 20, ideal: 60, max: 5 } },
        { id: "gameversion", label: "Game Version",               type: "text",     required: true, placeholder: "e.g. Build 42.0.5",                                                weight: 10, detailBonus: { min: 5, ideal: 4, max: 3 } },
        { id: "severity",    label: "Severity",                   type: "select",   required: true,  options: ["Critical — Game crash / data loss", "High — Major feature broken", "Medium — Minor feature broken", "Low — Cosmetic / visual issue"], weight: 10 },
        { id: "repro",       label: "Steps to Reproduce",         type: "textarea", required: true,  placeholder: "1. Go to...\n2. Click on...\n3. Observe...",                     weight: 30, detailBonus: { min: 50, ideal: 300, max: 10 } },
        { id: "expected",    label: "Expected Behavior",          type: "textarea", required: false,  placeholder: "What should have happened?",                                       weight: 20, detailBonus: { min: 30, ideal: 100, max: 5 } },
        //{ id: "actual",      label: "Actual Behavior",            type: "textarea", required: true,  placeholder: "What actually happened?",                                          weight: 15, detailBonus: { min: 30, ideal: 100, max: 5 } },
        { id: "platform",    label: "Platform",                   type: "select",   required: false, options: ["Windows 10", "Windows 11", "Linux", "macOS", "Steam Deck"],          weight: 10 },
        { id: "modlist",     label: "Other Active Mods",          type: "textarea", required: false, placeholder: "List other mods you're running (if relevant)",                     weight: 5, detailBonus: { min: 20, ideal: 100, max: 5 } },
        { id: "extra",       label: "Additional Context",         type: "textarea", required: false, placeholder: "Screenshots, log files, system specs, etc.",                       weight: 10, detailBonus: { min: 30, ideal: 150, max: 5 } },
        //{ id: "attachment",  label: "Attachment (Optional)",      type: "file",     required: false, accept: ".png,.jpg,.jpeg,.gif,.txt,.log,.zip,.json,.lua,.md", maxSize: 10485760, weight: 5 },
      ]
    },
    feature: {
      label: "Feature Request",
      githubLabel: "enhancement",
      fields: [
        { id: "title",       label: "Feature Title",              type: "text",     required: true,  placeholder: "Short, descriptive title",                                         weight: 15, detailBonus: { min: 20, ideal: 60, max: 5 } },
        { id: "category",    label: "Category",                   type: "select",   required: true,  options: ["Gameplay", "UI / UX", "Performance", "Compatibility", "Accessibility", "Other"], weight: 10 },
        { id: "description", label: "Description",                type: "textarea", required: true,  placeholder: "Describe the feature you'd like to see",                           weight: 25, detailBonus: { min: 50, ideal: 200, max: 10 } },
        { id: "usecase",     label: "Use Case / Motivation",      type: "textarea", required: true,  placeholder: "Why is this feature valuable? What problem does it solve?",        weight: 25, detailBonus: { min: 50, ideal: 200, max: 10 } },
        { id: "extra",       label: "Additional Context",         type: "textarea", required: false, placeholder: "Mockups, examples, etc.",                                           weight: 10, detailBonus: { min: 30, ideal: 150, max: 5 } },
        //{ id: "attachment",  label: "Attachment (Optional)",      type: "file",     required: false, accept: ".png,.jpg,.jpeg,.gif,.txt,.log,.zip,.json,.lua,.md", maxSize: 10485760, weight: 5 },
      ]
    }
  },
};
