name: Custom Pages Deployment with Mods JSON

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Generate mods.json
        run: python .github/scripts/generateJson.py
        env:
          CHUCK_PAT: ${{ secrets.CHUCK_PAT }}

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Adjust if you build into a subdirectory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2